_target_: lever_lm.models.v1.adapter_builder.build_model_v1_with_adapter

# PointerSelectorV1Config 参数（传递给 build_model_v1 的 config 参数）
config:
  _target_: lever_lm.models.v1.pointer_selector_v1.PointerSelectorV1Config
  d_model: 512
  K: 2
  shot_num: 2
  label_smoothing: 0.0
  dropout: 0.5

# 适配器参数
clip_name: openai/clip-vit-base-patch32
query_encoding_flag: ['image', 'text']
icd_encoding_flag: ['image', 'text']
adapter: false
norm: true

