version: local
name: okvqa
train_ds_len: 9009  # OKVQA 训练集只有 9009 个样本，建议 sample_num 设置为 800-1000
train_path: ${oc.env:OKVQA_PATH}/okvqa_hf/vqav2_mscoco_train2014.json
val_path: ${oc.env:OKVQA_PATH}/okvqa_hf/vqav2_mscoco_val2014.json
train_coco_dataset_root: ${oc.env:COCO_PATH}/mscoco2014/train2014
val_coco_dataset_root: ${oc.env:COCO_PATH}/mscoco2014/val2014

# use for eval
val_ques_path: ${oc.env:OKVQA_PATH}/OpenEnded_mscoco_val2014_questions.json
val_ann_path: ${oc.env:OKVQA_PATH}/mscoco_val2014_annotations.json

train_ques_path: ${oc.env:OKVQA_PATH}/OpenEnded_mscoco_train2014_questions.json
train_ann_path: ${oc.env:OKVQA_PATH}/mscoco_train2014_annotations.json

